version: '3.4'

services:
  # PHP Service
  app:
    container_name: '${COMPOSE_PROJECT_NAME}-php'
    mem_limit: 512m
    mem_reservation: 128M
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - database
      - redis
      - laravel_echo_server
    networks:
      - devHive

  # Nginx Service
  webserver:
    container_name: '${COMPOSE_PROJECT_NAME}-nginx'
    mem_limit: 512m
    mem_reservation: 128M
    tty: true
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - laravel_echo_server
    networks:
      - devHive

  # DB UI management service
  phpmyadmin:
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    mem_limit: 512m
    mem_reservation: 128M
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2048M
      MEMORY_LIMIT: 512M
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - database

  #MySQL Service
  database:
    container_name: '${COMPOSE_PROJECT_NAME}-mysql'
    mem_limit: 512m
    mem_reservation: 128M
    tty: true
    image: mysql:8.0
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - .docker/data/db:/var/lib/mysql/

  laravel_echo_server:
    container_name: '${COMPOSE_PROJECT_NAME}-laravel-echo'
    mem_limit: 512m
    mem_reservation: 128M
    tty: true
    build:
      context: .docker/laravel-echo-server
      dockerfile: Dockerfile
    volumes:
      - .env:/app/.env
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - devHive

  redis:
    container_name: '${COMPOSE_PROJECT_NAME}-redis'
    mem_limit: 512m
    mem_reservation: 128M
    tty: true
    image: redis:latest
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - devHive

networks:
  devHive:
    driver: bridge

volumes:
  database:
  redis: